### ISSUE TITLE
Initial Project Gradle files will not sync

### ISSUE THREAD

**Issue by srseibs** [probelalkhan/mini-tales#1]
The initial project setup (build.gradle files) will not sync.

I followed all the instructions in the video, and in desparation copy/pasted the entire content of these App and Project build.gradles from the tutorial-snapshots/#1-Project-Setup.

### In the **build.gradle(MiniTales) and build.gradle(:app)**, the "libs" is errored (underined in red):  

>  val Project.libs: LibrariesForLibs' can't be called in this context by implicit receiver. Use the explicit one if necessary

```
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.ktlint) apply false
    alias(libs.plugins.spotless) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.hilt) apply false
}
```

### In the **build.gradle(:app)** , the "projects" symbol is red and errored, as well as  "kapt". 

> Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
> public val TaskContainer.projects: TaskProvider<ProjectReportTask> defined in org.gradle.kotlin.dsl

```
dependencies {
    implementation(projects.theme)
    implementation(projects.network)
    implementation(projects.storage)
    implementation(projects.common)
    implementation(projects.common.data)
    implementation(projects.common.domain)
   . . .
```
 "kapt" reference is unresolved, but strangely the "libs" symbols are fine here in the implementation() functions ...
```
    implementation(libs.androidx.compose.navigation)
    implementation(libs.androidx.hilt.compose.navigation)

    implementation(libs.hilt)
    kapt(libs.hilt.compiler)
```

**Comment by probelalkhan** [comment]
You are using the projects as dependency that is not yet created in the initial setup. Instead of copy pasting, just extract #1-Project-Setup.zip from tutorial-snapshot. 
Inside this zip you have MiniTalesApp, directly open this to your Android Studio and see if it compiles properly or not. 
Thank You

**Comment by srseibs** [comment]
Ok, that seemed to work. The "project" missing symbols seemed to be the root cause, and that was because I was including some implementations(project:*) too soon for this course. Unclear why that would result in the "libs" symbol errors, but it seems like it did.

Thanks! you can close this issue.

**Comment by srseibs** [comment]
Copied too much of the project code.
